### ISSUE TITLE
Asking for email address permission

### ISSUE THREAD

**Issue by Safrone** [Dalimil/Find-and-Replace-Browser-Extension#18]
This is a great little extension that has saved me a lot of time in certain situations!

Recently, chrome disabled the extension saying that it requires to "Know your email address":

![Screenshot from 2019-09-05 13-52-19](https://user-images.githubusercontent.com/14047377/64366738-db490680-cfe4-11e9-8c96-2a7c4ce6d3a3.png)

Is there a reason for this permission because I have no idea why this extension would need that?

**Comment by Dalimil** [comment]
It's being acquired by another developer team, and going forward I sadly
won't have any control over it's future... You can probably keep the
extension's old version if this matters to you.

**Comment by dfinster** [comment]
What is the license for v1.3.17, is it possible for us to fork a non-privacy intrusive version?

**Comment by Dalimil** [comment]
This GitHub repository still belongs to me, their code will build on top of
mine and will be private, as far as I know. This repository won't be
receiving any updates, and will keep my last released version - 1.3.17 -
which has no specific license, but you are welcome to use it (if going
forward you are not satisfied with their development), and other people
have forked this repository in the past.

Of course, to use it, you'd need to `yarn build` the search widget folder
and then load this as a developer extension in your browser by loading the
main folder with the manifest (now also containing the previously built
search widget code bundle)

**Comment by dfinster** [comment]
It is a critical part of our business workflow, so we may indeed be interested to fork it internally for our company use and ensure it remains available for our internal processes. We have no plans to modify or re-release it, so we will take your offer to use version 1.3.17 internally.

Thank you for the update, and thank you for your excellent code!

**Comment by dfinster** [comment]
A brief review of the 1.3.19 version from the new developer "ALP Ventures LLC" reveals a bit more... 

The Stripe payment API is now included, and some new CSS classes have been added: 
- .pay-text
- .pay-button
- .pay-info.

Is there any chance to get an official open-source license for version 1.3.17?

**Comment by Dalimil** [comment]
I'll have a think and will look into this when I'm back from vacation on
the 10th of September.

**Comment by JeremyLee** [comment]
> Is there any chance to get an official open-source license for version 1.3.17?

It appears that at least part of it is licensed under the `MIT` license. See [package.json](https://github.com/Dalimil/Find-and-Replace-Browser-Extension/blob/4fe754f7e6537dee73e234538a85de1607c5d70a/search-widget/package.json)

**Comment by dfinster** [comment]
The Firefox version says it's under the MPL 2.0, is this correct? 
https://addons.mozilla.org/en-US/firefox/addon/find-replace-for-text-editing/

I experimented with the new 1.3.19 version. It demands $3.99 per month to use the "Favorites" feature. So far, we've dropped back to loading 1.3.17 in developer mode. Also, (not) helpfully, this means we lost all our regex saved favorites during the shuffle.
 
<img width="431" alt="Annotation 2019-09-07 124811" src="https://user-images.githubusercontent.com/18128717/64478255-df575e80-d173-11e9-9542-600bbf33c93f.png">

**Comment by dfinster** [comment]
> It appears that at least part of it is licensed under the `MIT` license. See [package.json](https://github.com/Dalimil/Find-and-Replace-Browser-Extension/blob/4fe754f7e6537dee73e234538a85de1607c5d70a/search-widget/package.json)

@JeremyLee  Good catch, I missed that.

**Comment by Dalimil** [comment]
It's under MPL 2.0, because that's what Firefox required for publishing on their extension store. I updated the README to explain that this repository won't be actively maintained and doesn't reflect the published extension anymore. It's being worked on by another team, but I think they won't be sharing the source code. Direct any issues or feedback to them directly.
