### ISSUE TITLE
Breakout support-website into own repo

### ISSUE THREAD

**Issue by janpio** [Dalimil/Find-and-Replace-Browser-Extension#6]
Today I installed (and later uninstalled) this extension. The extension didn't really solve my problem (couldn't execute the search & replace with one shortcut, so took the same amount of click than doing it manually) - Still nice extension though! - but I really like the install and uninstall experience.

Lots of extensions are missing this completely. I think you could definitely get some usage of it if you break it out into its own repository and document where and how to implement the install and uninstall opening.

**Comment by Dalimil** [comment]
Thanks for the feedback. Regarding shortcuts: open with Ctrl + Shift + F, then switch to replace field with Tab, then press Shift + Enter to replace all.

**Comment by janpio** [comment]
(Yep, what I used. I had to replace an easy to select URL, so my workflow then was Select > Ctrl + V only. As the extension also didn't focus the input field, I couldn't use a shortcut to send the form. Had hoped there would be one shortcut to replace all directly.)

**Comment by janpio** [comment]
For reference: 

This is what opens the page on install and uninstall: https://github.com/Dalimil/Find-and-Replace-Browser-Extension/blob/d63ccc6cd4095ac65506d352df75c049ac6d41fb/main/src/background.js#L4-L14

**Comment by Dalimil** [comment]
This is clearly documented in the official Chrome extension documentation: https://developer.chrome.com/extensions/runtime#event-onInstalled
Mozilla has examples too: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/setUninstallURL
